//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cuentas.Ar.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Objetivo
    {
        public int idObjetivo { get; set; }
        public int idUsuario { get; set; }
        public int idEstadoObjetivo { get; set; }
        public int idMoneda { get; set; }
        public string Motivo { get; set; }
        public decimal Importe { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime FechaVencimiento { get; set; }
    
        public virtual EstadoObjetivo EstadoObjetivo { get; set; }
        public virtual Moneda Moneda { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
