//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cuentas.Ar.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recordatorio
    {
        public int idRecordatorio { get; set; }
        public int idEstado { get; set; }
        public int idCategoria { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime Fecha { get; set; }
        public System.DateTime FechaVencimiento { get; set; }
    
        public virtual Categoria Categoria { get; set; }
        public virtual EstadoRecordatorio EstadoRecordatorio { get; set; }
    }
}
